<a href="https://colab.research.google.com/github/Dhruxp/MOSSAI/blob/main/deeplearning_francoischollet/TensorFlowBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
x = tf.ones(shape = (2,1))
x

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>

In [2]:
y = tf.zeros(shape=(2,1))
y

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.],
       [0.]], dtype=float32)>

In [3]:
from numpy import shape
tf.random.normal(shape=(3,1),mean=0.,stddev=1.)


<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[-1.6669589 ],
       [-0.18139876],
       [ 0.7046135 ]], dtype=float32)>

Tensorflow tensors are non assignabke x[0,0] = 0 is a BS statement
This assignment is true for numpys

In [4]:
# initialise a tensorflow variable
v = tf.Variable(initial_value=tf.random.normal(shape=(3,1)))
v

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[-1.5071883 ],
       [ 0.49618328],
       [-0.8209474 ]], dtype=float32)>

In [5]:
#modify using the assign operator
v.assign(tf.ones((3,1)))

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>

In [6]:
v[0,0].assign(3.)

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [1.],
       [1.]], dtype=float32)>

Assignment is asllowed if .assign is used
### assign_add(), assign_sub() are +=,-=


In [7]:
v.assign_add(tf.ones((3,1)))


<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[4.],
       [2.],
       [2.]], dtype=float32)>

TensorFlow allows to retrieve the gradient of any differentiable equation with respect to any of it's inputs

In [8]:
input_var = tf.Variable(initial_value= 3)
with tf.GradientTape() as tape:
  result = tf.square(input_var) # this is an eager execution
gradient = tape.gradient(target=result,sources=input_var)

Most commonly this is used to retrieve the gradients of the loss of a model wrt it's weights

In [9]:
time = tf.Variable(0.)
with tf.GradientTape() as outer_tape:
  with tf.GradientTape() as inner_tape:
    position = 4.9*time**2
  speed = inner_tape.gradient(position, time)
  acceleration = outer_tape.gradient(speed,time)

For any tensor the .ndim command allows us to see it's rank.
For any tensor the .shape command shows the shape and the .dtype shows the tensor datatype which are the fundamental parameters to describe a tensor

Tensors can be subject to slicing just like lists.

## Vector Data

A rank 2 tensor because every single data point will be encoded as a vector and a whole bunch of these will end up forming a rank 2 tensor

In [11]:
import numpy as np
data = np.array([
    [18, 172, 65, 4.5],
    [19, 168, 58, 3.0],
    [17, 180, 72, 5.0],
    [18, 175, 70, 2.5]
])
# Let this be a student database of age, height, weight, gpa. Each student is a vector and the class of students is a rank 2 tensor
data


array([[ 18. , 172. ,  65. ,   4.5],
       [ 19. , 168. ,  58. ,   3. ],
       [ 17. , 180. ,  72. ,   5. ],
       [ 18. , 175. ,  70. ,   2.5]])

In this the 0 axis is the sample axis and the remaining are feature axes

## Timeseries Data

This is when a rank 2 tensor has a time component that is associated with it so a seperate attribute for time will be tracked

In [12]:

data = np.random.random((7, 24, 3))


In [13]:
data

array([[[0.21369933, 0.09566295, 0.95117163],
        [0.69163361, 0.46598368, 0.89101033],
        [0.20609935, 0.65847065, 0.59188441],
        [0.33345466, 0.64858993, 0.03150883],
        [0.25859619, 0.73485497, 0.48577263],
        [0.52348501, 0.78485751, 0.75622235],
        [0.89547182, 0.82514669, 0.7915613 ],
        [0.24534324, 0.82528586, 0.69784058],
        [0.50867438, 0.25127477, 0.59574757],
        [0.72811085, 0.77728647, 0.899082  ],
        [0.68413123, 0.43310738, 0.89233406],
        [0.86500462, 0.70284695, 0.59684621],
        [0.0936846 , 0.58603221, 0.95377862],
        [0.55946935, 0.14661753, 0.66352575],
        [0.26541591, 0.5628471 , 0.81110771],
        [0.65066492, 0.45678636, 0.19807967],
        [0.79214494, 0.44889077, 0.84176884],
        [0.80365766, 0.85880997, 0.46669276],
        [0.59717422, 0.71545281, 0.15649284],
        [0.32998245, 0.48310672, 0.15939114],
        [0.09991036, 0.16939127, 0.21506428],
        [0.37381566, 0.69240304, 0

## Image Data

An image data is a rank 4 dataset that has color channels, height, width, samples

In [14]:
data = np.random.random((100, 64, 64, 3))
data.shape

(100, 64, 64, 3)

## Video Data

Any video data is a rank 5 tensor with all 4 attributes of an image and frames as the extra attribute

In [15]:
data = np.random.random((20, 300, 128, 128, 3))
data.shape

(20, 300, 128, 128, 3)

## Tensor operations

Relu = Rectified linear unit, This is a function that does the following:
Relu(x) = max(0,x)
So if x is positive then Relu is x otherwise it's 0

Element-wise relu operation

In [17]:
def basic_relu(x):
  assert len(x.shape) == 2
  x = x.copy()
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i,j] = max(x[i,j],0)
  return x
x = np.array([
    [-2, -1,  0],
    [ 1, -3,  4]
])
basic_relu(x)


array([[0, 0, 0],
       [1, 0, 4]])

This element wise operation is heavily optimised in NumPy is allots the data to BLAS programs automatically killing the workload

In [19]:
def basic_add(x,y):
  assert len(x.shape) == 2
  assert x.shape == y.shape
  x = x.copy()
  for i in range(x.shape[0]):
    for j in range(x.shape[1]):
      x[i,j] += y[i,j]
  return x
# similar can be defined for multiplication as well

In [20]:
# test the time difference between our naive functions and the inbuilt numpy functions
import time
x = np.random.random((20,100))
y = np.random.random((20,100))
t0 = time.time()
for _ in range(1000):
  z = x+y
  z = np.maximum(z,0.)
print("took: {0:.2f} s".format(time.time() - t0))


took: 0.01 s


In [21]:
t0 = time.time()
for _ in range(1000):
  z = basic_relu(z)
  z = basic_add(x,y)
print("took: {0:.2f} s".format(time.time() - t0))

took: 1.89 s


### 0.01s vs 1.89s