<a href="https://colab.research.google.com/github/Dhruxp/MOSSAI/blob/main/deeplearning_francoischollet/TensorFlowBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
x = tf.ones(shape = (2,1))
x

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>

In [3]:
y = tf.zeros(shape=(2,1))
y

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.],
       [0.]], dtype=float32)>

In [5]:
from numpy import shape
tf.random.normal(shape=(3,1),mean=0.,stddev=1.)


<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[ 0.57005435],
       [-0.620822  ],
       [ 0.37005737]], dtype=float32)>

Tensorflow tensors are non assignabke x[0,0] = 0 is a BS statement
This assignment is true for numpys

In [6]:
# initialise a tensorflow variable
v = tf.Variable(initial_value=tf.random.normal(shape=(3,1)))
v

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[-0.6547747 ],
       [ 1.9049326 ],
       [ 0.09175112]], dtype=float32)>

In [7]:
#modify using the assign operator
v.assign(tf.ones((3,1)))

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>

In [8]:
v[0,0].assign(3.)

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [1.],
       [1.]], dtype=float32)>

Assignment is asllowed if .assign is used
### assign_add(), assign_sub() are +=,-=


In [9]:
v.assign_add(tf.ones((3,1)))


<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[4.],
       [2.],
       [2.]], dtype=float32)>

TensorFlow allows to retrieve the gradient of any differentiable equation with respect to any of it's inputs

In [11]:
input_var = tf.Variable(initial_value= 3)
with tf.GradientTape() as tape:
  result = tf.square(input_var) # this is an eager execution
gradient = tape.gradient(target=result,sources=input_var)

Most commonly this is used to retrieve the gradients of the loss of a model wrt it's weights

In [14]:
time = tf.Variable(0.)
with tf.GradientTape() as outer_tape:
  with tf.GradientTape() as inner_tape:
    position = 4.9*time**2
  speed = inner_tape.gradient(position, time)
  acceleration = outer_tape.gradient(speed,time)