In [1]:
import torch
print(torch.__version__)

2.9.0+cpu


TENSORS:
It's similar to a list or a numpy array. 
Suitable for GPUs
It's a matrix of any dimension but with the SAME DATATYPE
Float32 = Datatype
torch.tensor(#any numpy array): Will convert a numpy array to a tensor and changes it's default datatype. 
Documentatio to refer to: https://docs.pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html

In [2]:
#tensor creation
import torch
ten2d = torch.randn(3,4)
print(ten2d)
tens3d = torch.randn(3,4,5)
print(tens3d)

tensor([[-1.6703,  0.9716,  0.3468,  0.0862],
        [ 1.0739,  0.8099,  0.6283,  0.1670],
        [ 0.0151,  0.9095,  0.3226,  1.2161]])
tensor([[[-2.3946,  0.8305, -0.7504, -0.2849,  1.6002],
         [ 0.4997, -0.4129,  0.6693,  0.3737, -0.2583],
         [-0.6386, -2.1268,  0.0523, -0.5860,  1.3350],
         [-0.0077, -0.4083, -2.8380, -0.8718, -0.2604]],

        [[ 0.5390, -0.0314,  0.1360,  1.0056, -0.3368],
         [-0.1732, -1.0834, -0.4416, -1.3565, -0.8521],
         [ 0.3492,  1.5907, -0.3237, -1.3070,  0.0975],
         [-0.5559,  2.7112, -0.2034, -0.6764,  0.2074]],

        [[-1.5280,  0.1103, -1.2932,  0.1197, -0.6283],
         [ 1.0053, -1.1501, -1.3741,  1.0888,  0.5615],
         [-0.8079,  1.1772,  1.5705, -0.4413,  0.1529],
         [-2.2979,  1.3526,  0.4256,  0.7030,  1.1321]]])


TENSOR OPERATIONS:
1. Reshape: Reshapes the existing tensor into a matrix of any given dimension. The view function also works simlarly
Error is thrown if the reshape dimension is asking for more than the number of present elements
If the number of elements is unknown we can rearrange using -1 as the number of columns but the number of rows have to be specified and the data should be able to fit in the given dimension workspace. We can also use -1 in the rows but the number of columns have to be specified then. Atleast one parameter row or column must be a known value.
2. View: The view function works exactly like the reshape, but very minute differences are present between the 2. 
When the above functions are used the changes to the original tensor will show in the reshaped one as well so any number updated in the original tensor will show up even on the reshaped tensor.
3. Slices: Like slicing an array we can access parts of the tensor using slicing


In [3]:
import torch
mytensor = torch.arange(1,10)
print(mytensor)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [4]:
mytensor1 = mytensor.reshape(3,3)
print(mytensor1)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [6]:
mytensor2= mytensor1[:,1]
print(mytensor2)
mytensor3= mytensor1[1,:]
print(mytensor3)
mytensor4= mytensor1[:,1:]
print(mytensor4)
mytensor5= mytensor1[1:3,0:2]
print(mytensor5)

tensor([2, 5, 8])
tensor([4, 5, 6])
tensor([[2, 3],
        [5, 6],
        [8, 9]])
tensor([[4, 5],
        [7, 8]])


TENSOR ARITHMATIC:
1. Add: Use + operator between two tensors, torch.add(t1,t2) will do the same thing. Will add each item with the corresponding item in the other tensor.
2. Suntract: Use - operator, torch.sub(t1,t2) will perform the same activity
3. Multiplication: Use * Operator, torch.mul(t1,t2) will perform the same activity
4. Division: Use / operator, THIS WILL CONVERT EACH MEMBER TO A FLOAT. torch.div(t1,t2) will perform the same activity
5. Remainder: Use % operator for the modulus, torch.remainder(t1,t2) will perform the same activity
6. Exponents: torch.pow(t1,t2), this is t1**t2
Note:
t1.add_(t2) functions as t1=t1+t2. This is reassignment

In [8]:
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([4,5,6])
t3 = t1 + t2
print(t3)   
#t4 = torch.matmul(t1.float(), t2.float())
#print(t4)       
t5 = t1 - t2
print(t5)
t6 = t1 * t2
print(t6)   
t7 = t2 / t1
print(t7)   
t8 = t1%t2
print(t8)   
t9 = torch.pow(t1,t2)
print(t9)

tensor([5, 7, 9])
tensor([-3, -3, -3])
tensor([ 4, 10, 18])
tensor([4.0000, 2.5000, 2.0000])
tensor([1, 2, 3])
tensor([  1,  32, 729])
